# Generated by Django 5.0.4 on 2024-04-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_password_hash_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_receiver', to='chat.user'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_sender', to='chat.user'),
        ),
    ]
