# Generated by Django 5.0.4 on 2024-04-25 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_desc', models.TextField()),
                ('magnitude', models.IntegerField()),
                ('occur_time', models.DateTimeField()),
                ('depth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EarthquakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField()),
                ('earthquake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.earthquake')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.location')),
            ],
        ),
    ]
