# Generated by Django 5.0.4 on 2024-04-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_earthquake_location_earthquakerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earthquakerecord',
            old_name='earthquake',
            new_name='e_id',
        ),
        migrations.RenameField(
            model_name='earthquakerecord',
            old_name='location',
            new_name='l_id',
        ),
    ]
