# Generated by Django 5.0.4 on 2024-04-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_earthquake_earthquakerecord_e_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake',
            name='earthquake_number',
            field=models.IntegerField(default=0),
        ),
    ]
