# Generated by Django 5.0.4 on 2024-04-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_earthquake_earthquake_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chatroom_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
